SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{60569780DE4EE17A}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{691D4249E8FA993B}" {
     m_sEntityPrefab "{4A2EC4B5EAA232E0}Prefabs/Vehicles/Tracked/M1A2/M1A2_Woodland.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{691D4249E8FA9AAA}" {
      }
      SCR_EntityCatalogSpawnerData "{691D4249E8FA9AAF}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{691D4249E9363FF3}" {
     m_sEntityPrefab "{CE4C2B81BFAA47E5}Prefabs/Vehicles/Tracked/M1A2/M1A2_Tan.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{691D4249E9363F89}" {
      }
      SCR_EntityCatalogSpawnerData "{691D4249E9363F8A}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{691D4249F7AE9815}" {
     m_sEntityPrefab "{622AC75CB666FF70}Prefabs/Vehicles/Tracked/M1A2/SEP/M1A2_Woodland_SEP.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{691D4249F7AE99BA}" {
      }
      SCR_EntityCatalogSpawnerData "{691D4249F7AE99BF}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{691D4249F4CD9441}" {
     m_sEntityPrefab "{30A9A11001275C84}Prefabs/Vehicles/Tracked/M1A2/SEP/M1A2_Tan_SEP.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{691D4249F4CD941F}" {
      }
      SCR_EntityCatalogSpawnerData "{691D4249F4CD95E0}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
   }
  }
 }
}