SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{60569780DE4EE17A}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{68CCB397E67CD5DA}" {
     m_sEntityPrefab "{A31B9C9D96E0BF68}Prefabs/Vehicles/Wheeled/Stryker/Stryker_Cage_MERDC.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{68CCB397E67CD52E}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{68CCB397E67CD530}" {
       m_eSlotTypes 54
      }
     }
    }
    SCR_EntityCatalogEntry "{68CCB397F28B70A6}" {
     m_sEntityPrefab "{2AFBAB30EC3850F2}Prefabs/Vehicles/Wheeled/Stryker/Stryker_CROWS_Javelin_MERDC.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{68CCB397F28B705A}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{68CCB397F28B705F}" {
       m_eSlotTypes 54
      }
     }
    }
    SCR_EntityCatalogEntry "{68CCB397FDD3FD47}" {
     m_sEntityPrefab "{CF0A8EB2CB90701C}Prefabs/Vehicles/Wheeled/Stryker/Stryker_Dragoon_Cage.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{68CCB397FDD3FEE1}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{68CCB397FDD3FEE2}" {
       m_eSlotTypes 54
      }
     }
    }
    SCR_EntityCatalogEntry "{68CCB3970488CF97}" {
     m_sEntityPrefab "{3BBAB8769FA8384E}Prefabs/Vehicles/Wheeled/Stryker/Stryker_MGS_MERDC.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{68CCB3970488CF0C}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{68CCB3970488CF11}" {
       m_eSlotTypes 54
      }
     }
    }
    SCR_EntityCatalogEntry "{68C327C4A3F558B1}" {
     m_sEntityPrefab "{89A9D5D7D758ED50}Prefabs/Vehicles/Tracked/M1A2/M1A2_SEPV2_TUSK_MERDC_T1.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{68C327C4A3F4154F}" {
      }
      SCR_EntityCatalogSpawnerData "{68C327C4A3F41543}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{60569780DC27DDBC}" {
  }
 }
}