SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{69287642C13136D1}" {
   m_sIdentifier "JLTVs"
   m_aEntities {
    SCR_EntityCatalogEntry "{6912189D7A63316D}" {
     m_sEntityPrefab "{90242B1302DB429F}Prefabs/Vehicles/Tracked/M1A2/M1A2_D1.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{6912189D7335F123}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{6912189D7335F126}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
      SCR_EntityCatalogEditorData "{64D93152C8600528}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{64DCBB06AA1E41E1}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{692748DE3F12779F}" {
     m_sEntityPrefab "{8765EC9F88852B98}Prefabs/Vehicles/Tracked/BFV/M2A3_BUSK_D1.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{692748DE3F12771E}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{692748DE3F1278E2}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
      SCR_EntityCatalogEditorData "{64D93152C8600528}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{64DCBB06AA1E41E1}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{6912189E85DD6664}" {
     m_sEntityPrefab "{8BD82C0F86E9357F}Prefabs/Vehicles/Tracked/M1A2/M1A2_D6.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{6912189E85DD67F6}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{6912189E85DD67EA}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
      SCR_EntityCatalogEditorData "{64D93152C8600528}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{64DCBB06AA1E41E1}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
   }
  }
 }
}